### ISSUE TITLE
build -? is busted

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/buildtools#1305]
In CoreFX

```
C:\git\corefx.dan>build managed -?
Tools are already initialized.
Error: Object reference not set to an instance of an object.    at Microsoft.DotNet.Execute.Setup.FormatSetting(String option, String value, String type, String toolName)
   at Microsoft.DotNet.Execute.Setup.BuildParametersForCommand(Dictionary`2 commandParameters, String toolName)
   at Microsoft.DotNet.Execute.Setup.BuildCommand(String commandSelectedByUser, List`1 parametersSelectedByUser, Dictionary`2 parameters)
   at Microsoft.DotNet.Execute.Setup.GetHelpCommand(String commandName, String alias)
   at Microsoft.Fx.CommandLine.CommandLineParser.GetHelp(Int32 maxLineWidth, String parameterSetName, Boolean displayGlobalQualifiers)
   at Microsoft.Fx.CommandLine.CommandLineParser.<>c.<ParseForConsoleApplication>b__0_0(CommandLineParser parser)
   at Microsoft.Fx.CommandLine.CommandLineParser.Parse(Action`1 parseBody, Action`1 helpHandler, Action`2 errorHandler, Setup setupContent, String[] args)
   at Microsoft.Fx.CommandLine.CommandLineParser.ParseForConsoleApplication(Action`1 parseBody, String[] args, Setup setupContent)
   at Microsoft.DotNet.Execute.Executor.DefineParameters(String[] args, Setup setupInformation)

```

**Comment by weshaggard** [comment]
cc @MattGal

**Comment by danmosemsft** [comment]
@MattGal it would be nice  to fix this since many people are doing -? to look for any new build parameters.

**Comment by stephentoub** [comment]
> since many people are doing -? to look for any new build parameters

Especially because the error message you get when you use an invalid parameter says to use "-?" to find the right one.

**Comment by MattGal** [comment]
I will look at this today.

**Comment by MattGal** [comment]
Addressed this in https://github.com/dotnet/buildtools/pull/1313 ,  however the command:

**build managed -?** is not going to do what I think the user might expect, since build.cmd/sh does native build then managed build sequentially, thus showing the help info for native then managed in order.

The subsequent fix to make this really work would be to parse for managed in the 2nd arg before shelling off to run.exe, if that's what we want to do.

**Comment by danmosemsft** [comment]
fixed enough
