### ISSUE TITLE
System.Exception - Failed to remove directory... error=18

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/buildtools#1694]
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=1014332

```
2017-09-25T21:23:11.8604541Z   Will retry again in 2000 ms
2017-09-25T21:23:13.8813446Z   Attempting to cleanup E:\A\_work\1216 ... 
2017-09-25T21:23:13.8813446Z   Failed in cleanup attempt... 1 retries left.
2017-09-25T21:23:13.8813446Z   System.Exception - Failed to remove directory '\\?\E:\A\_work\1216\s\src': error=18, error code values are described at https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx
2017-09-25T21:23:13.8813446Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.ThrowIfWindowsErrorCode(String message)
2017-09-25T21:23:13.8813446Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.RemoveDirectoryLongPath(String directory)
2017-09-25T21:23:13.8813446Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.RemoveDirectoryRecursiveLongPath(String directory)
2017-09-25T21:23:13.8813446Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.RemoveDirectoryRecursiveLongPath(String directory)
2017-09-25T21:23:13.8813446Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.RemoveDirectoryRecursiveLongPath(String directory)
2017-09-25T21:23:13.8813446Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.<CleanupDirectoryAsync>d__54.MoveNext()
2017-09-25T21:23:13.8813446Z   Will retry again in 2000 ms
2017-09-25T21:23:15.8889461Z   Attempting to cleanup E:\A\_work\1216 ... 
2017-09-25T21:23:15.8889461Z   Failed in cleanup attempt... 0 retries left.
2017-09-25T21:23:15.8889461Z   System.Exception - Failed to remove directory '\\?\E:\A\_work\1216\s\src': error=18, error code values are described at https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx
2017-09-25T21:23:15.8889461Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.ThrowIfWindowsErrorCode(String message)
2017-09-25T21:23:15.8889461Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.RemoveDirectoryLongPath(String directory)
2017-09-25T21:23:15.8889461Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.RemoveDirectoryRecursiveLongPath(String directory)
2017-09-25T21:23:15.8889461Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.RemoveDirectoryRecursiveLongPath(String directory)
2017-09-25T21:23:15.8889461Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.RemoveDirectoryRecursiveLongPath(String directory)
2017-09-25T21:23:15.8889461Z      at Microsoft.DotNet.Build.Tasks.CleanupVSTSAgent.<CleanupDirectoryAsync>d__54.MoveNext()
```

**Comment by danmosemsft** [comment]
8 = ERROR_NO_MORE_FILES. The code is not doing FindNextFile. I don't know why RemoveDirectory is returning this. Is there something else concurrently progressively deleting its contents?

@JeremyKuhne do you know what can cause this?

**Comment by Chrisboh** [comment]
@jcagme With your fix did this issue get fixed as well?

**Comment by Chrisboh** [comment]
After a quick look it @MattGal thinks this is now fixed.  If you are still seeing any issues please reopen.
