### ISSUE TITLE
Run.exe crashes on a config.json that doesn't have tools linked up correctly

### ISSUE THREAD

**Issue by TyOverby** [dotnet/buildtools#890]
~~I have no idea why this file is considered malformed, but~~ this config.json breaks run.exe

```json
{
    "settings": {},

    "commands": {
        "sync": {
            "alias": {
                "p": {
                    "description": "Restores all NuGet packages for repository",
                    "settings": {}
                }
            },
            "defaultValues": {
                "toolName": "restore",
                "settings": {}
            }
        }
    },

    "tools": {
        "restore": {
            "run": {
                "windows": "restore.cmd",
                "unix": "foo"
            },
            "valueTypes": {}
        }
    }
}
```

error:
```
C:\Users\tyoverby\workspace\roslyn-internal\Open>run sync -?
Tools are already initialized.
Running: C:\Users\tyoverby\workspace\roslyn-internal\Open\Tools\dotnetcli\dotnet.exe C:\Users\tyoverby\workspace\roslyn-internal\Open\Tools\run.exe sync -?
Error: The process restore is not specified in the Json file.
Error: Object reference not set to an instance of an object.    at Microsoft.DotNet.Execute.Setup.GetHelpCommand(String commandName, String alias)
   at Microsoft.Fx.CommandLine.CommandLineParser.GetHelp(Int32 maxLineWidth, String parameterSetName, Boolean displayGlobalQualifiers)
   at Microsoft.Fx.CommandLine.CommandLineParser.<>c.<ParseForConsoleApplication>b__0_0(CommandLineParser parser)
   at Microsoft.Fx.CommandLine.CommandLineParser.Parse(Action`1 parseBody, Action`1 helpHandler, Action`2 errorHandler, Setup setupContent, String[] args)
   at Microsoft.Fx.CommandLine.CommandLineParser.ParseForConsoleApplication(Action`1 parseBody, String[] args, Setup setupContent)
   at Microsoft.DotNet.Execute.Executor.DefineParameters(String[] args, Setup setupInformation)
```

**Comment by TyOverby** [comment]
Apparently the only tools names that are valid are "terminal" and "msbuild".

**Comment by maririos** [comment]
As we talked yesterday, for now the Run Command Tool has a dependency on the tools: msbuild and terminal.
In a next iteration of Run we'll fix that.
