### ISSUE TITLE
Run.exe crashes when overriding Project in settings for an alias where project is a default value

### ISSUE THREAD

**Issue by TyOverby** [dotnet/buildtools#894]
```
{
    "settings": {
        "Project": {
            "description": "Project where the commands are going to be applied.",
            "valueType": "passThrough",
            "values": [],
            "defaultValue": ""
        }
    },

    "commands": {
        "build": {
            "alias": {
                "compilers": {
                    "description": "build the compilers",
                    "settings": {
                        "Project": "./Compilers.sln"
                    }
                }
            },
            "defaultValues": {
                "toolName": "msbuild",
                "settings": {
                    "Project": "./Roslyn.sln"
                }
            }
        },
        "sync": {
            "alias": { },
            "defaultValues": {
                "toolName": "terminal",
                "Project": "./restore",
                "settings": { }
            }
        },
        "clean": {
            "alias": { },
            "defaultValues": {
                "toolName": "terminal",
                "Project": "./clean",
                "settings": { }
            }
        }
    },

    "tools": {
        "msbuild": {
            "run": {
                "windows": "Tools/msbuild.cmd",
                "unix": "Tools/msbuild.sh"
            },
            "valueTypes": {
                "property": "/p:{name}={value}",
                "target": "/t:{name}",
                "internal": "/{name}"
            }
        },
        "terminal": {
            "run": {
                "windows": "cmd",
                "unix": "sh"
            },
            "valueTypes": {}
        }
    }
}
```

**Comment by TyOverby** [comment]
Running `run build` works fine, but `run build compilers` crashes with 

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Execute.Setup.FormatSetting(String option, String value, String type, String toolName)
   at Microsoft.DotNet.Execute.Setup.BuildParametersForCommand(Dictionary`2 commandParameters, String toolName)
   at Microsoft.DotNet.Execute.Setup.BuildCommand(String commandSelectedByUser, List`1 parametersSelectedByUser, Dictionary`2 parameters)
   at Microsoft.DotNet.Execute.Setup.ExecuteCommand(String commandSelectedByUser, List`1 parametersSelectedByUser)
   at Microsoft.DotNet.Execute.Executor.Main(String[] args)
```

**Comment by maririos** [comment]
@TyOverby I can't repro this. I'm using Build Tools version 1.0.26-prerelease-00615-02 and it is working.
What version are you using?

**Comment by TyOverby** [comment]
I'm using `1.0.26-prerelease-00615-02 `

**Comment by maririos** [comment]
The problem here is that you are not passing a `-` before the word compilers. That is how the tool recognices what an alias and a command is.
In my machine in fails saying that `compilers` is not a project msbuild knows about. But with the changes made with the PR #883 the error message is going to be different and more explicit.

Closing the issue.
